# Generated by Django 2.2.5 on 2021-04-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LOGIN', '0003_auto_20210405_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=100)),
                ('article_content', models.TextField()),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOGIN.User')),
            ],
        ),
    ]
