# Generated by Django 2.2.5 on 2021-04-06 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INDEX', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_tag', models.CharField(max_length=20)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INDEX.article')),
            ],
        ),
    ]
