# Generated by Django 2.2.5 on 2021-04-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INDEX', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_short',
            field=models.CharField(default='空', max_length=500),
            preserve_default=False,
        ),
    ]
