# Generated by Django 2.2.5 on 2021-03-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='nameless', max_length=100),
            preserve_default=False,
        ),
    ]
